### ISSUE TITLE
Allow install on Magento 2.3.x?

### ISSUE THREAD

**Issue by craigcarnell** [EaDesgin/magento2-pdf-generator2#63]
In composer.json, magento module versions can be specified with '*'

Also, php requirements are now: "php": "~7.1.3||~7.2.0",

**Comment by rishabhchd19** [comment]
it doesn't allow on CE 2.3.0.

my errr:
Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- magento/module-backend 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.1 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.0-rc3 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.0-rc2 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.1.24) does not satisfy that requirement.
- magento/module-backend 100.1.0-rc1 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.1.24) does not satisfy that requirement.
- Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
- eadesignro/module-eacore 0.2.9 requires magento/module-backend ^100.1.0| ^100.2.0 -> satisfiable by magento/module-backend[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.2.0-rc20, 100.2.0-rc21, 100.2.0-rc22, 100.2.0-rc23, 100.2.0-rc30, 100.1.4, 100.2.0, 100.2.1, 100.1.5, 100.1.6, 100.2.2, 100.1.7, 100.2.3, 100.1.8, 100.2.4, 100.2.5, 100.1.9, 100.1.10, 100.2.6, 100.1.11, 100.2.7].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0-rc20].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0-rc21].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0-rc22].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0-rc23].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0-rc30].
- Can only install one of: magento/module-backend[101.0.0, 100.2.0].
- Can only install one of: magento/module-backend[101.0.0, 100.2.1].
- Can only install one of: magento/module-backend[101.0.0, 100.2.2].
- Can only install one of: magento/module-backend[101.0.0, 100.2.3].
- Can only install one of: magento/module-backend[101.0.0, 100.2.4].
- Can only install one of: magento/module-backend[101.0.0, 100.2.5].
- Can only install one of: magento/module-backend[101.0.0, 100.2.6].
- Can only install one of: magento/module-backend[101.0.0, 100.1.11].
- Can only install one of: magento/module-backend[101.0.0, 100.2.7].
- eadesignro/module-pdfgenerator 1.2.4 requires eadesignro/module-eacore ^0.2.9 -> satisfiable by eadesignro/module-eacore[0.2.9].
- magento/product-community-edition 2.3.0 requires magento/module-backend 101.0.0 -> satisfiable by magento/module-backend[101.0.0].
- Installation request for eadesignro/module-pdfgenerator 1.2.4 -> satisfiable by eadesignro/module-pdfgenerator[1.2.4].

**Comment by eadesignro** [comment]
This was solved a few days ago.

**Comment by rishabhchd19** [comment]
Still getting an error after installing 1.2.5

There has been an error processing your request
Exception printing is disabled by default for security reasons.

I manually disabled the module from the composer to get back functional.
